version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: |
            sudo npm install -g npm@latest
      - run:
          name: Update Yarn
          command: |
            sudo apt-get update && sudo apt-get install apt-transport-https -y
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -y && sudo apt-get install yarn -y
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Execute Jest
          command: yarn test
      # - run:
      #     name: Code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          destination: tests
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results.xml

